misc: gas reporting after running tests (#243)

diff --git a/scripts/test b/scripts/test
--- a/scripts/test
+++ b/scripts/test
@@ -2,6 +2,60 @@
 
 set -eo pipefail
 
+MNEMONIC="myth like bonus scare over problem client lizard pioneer submit female collect"
+TESTRPC_PORT=8545
+
+### Functions
+
+evm_running() {
+  nc -z localhost "$TESTRPC_PORT"
+}
+
+evm_start() {
+  echo "Starting our own evm instance at port $TESTRPC_PORT"
+  npx ganache-cli -m "$MNEMONIC" -i 1337 --gasLimit 8000000 --port "$TESTRPC_PORT" > /dev/null &
+  evm_pid=$!
+}
+
+evm_kill() {
+  if evm_running; then
+    echo "Killing evm instance at port $TESTRPC_PORT"
+    kill -9 $(lsof -i:$TESTRPC_PORT -t)
+  fi
+}
+
+### Setup evm
+
+# Gas reporter needs to run in its own evm instance
+if [ "$RUN_EVM" = true  ]; then
+  evm_kill
+  evm_start
+  sleep 5
+fi
+
+# Exit error mode so the evm instance always gets killed
+set +e
+result=0
+
+### Main
+
 npm run compile
 npm run typechain
-buidler test
+
+if [ "$RUN_EVM" = true ]; then
+  # Run using the standalone evm instance
+  npx buidler test --network ganache
+  result=$?
+else
+  # Run using the default evm
+  npx buidler test "$@"
+  result=$?
+fi
+
+### Cleanup
+
+if [ "$RUN_EVM" = true ]; then
+  evm_kill
+fi
+
+exit $result
